<!DOCTYPE html>
<html>

<body>
	<table>
	
		<tr>
			<td>Name</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>

		<tr>
			<td>Phone No</td>
			<td>
				<?= $data['phone']; ?>
			</td>
		</tr>

		<tr>
			<td>Company Name
			</td>
			<td>
				<?= $data['company']; ?>
			</td>
		</tr>

		<tr>
			<td>Project Description
			</td>
			<td>
				<?= $data['project']; ?>
			</td>
		</tr>
		

		<tr>
			<td>Document
			</td>
			<td>
				<?= $data['upload_link']; ?>
			</td>
		</tr>

		
		


	</table>

</body>

</html>