<!DOCTYPE html>
<html>

<body>
	<table>
	
		<tr>
			<td>Name</td>
			<td>
				<?= $data['username']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>

		<tr>
			<td>Phone No</td>
			<td>
				<?= $data['phone']; ?>
			</td>
		</tr>

		<tr>
			<td>Emergency Contact
			</td>
			<td>
				<?= $data['ephone']; ?>
			</td>
		</tr>

		<tr>
			<td>Company Name
			</td>
			<td>
				<?= $data['companyname']; ?>
			</td>
		</tr>
		

		<tr>
			<td>Message
			</td>
			<td>
				<?= $data['message']; ?>
			</td>
		</tr>

		
		


	</table>

</body>

</html>