<!DOCTYPE html>
<html>

<body>
	<table>

		<tr>
			<td>Name</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Company Name</td>
			<td>
				<?= $data['Company']; ?>
			</td>
		</tr>

		<tr>
			<td>Address</td>
			<td>
				<?= $data['address']; ?>
			</td>
		</tr>

		<tr>
			<td>>Would you like to have the bill with GST?
			</td>
			<td>
				<?= $data['GST']; ?>
			</td>
		</tr>

		<tr>
			<td>Email
			</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>


		<tr>
			<td>Phone
			</td>
			<td>
				<?= $data['phone']; ?>
			</td>
		</tr>

		<tr>
			<td>City
			</td>
			<td>
				<?= $data['city']; ?>
			</td>
		</tr>

		<tr>
			<td>State
			</td>
			<td>
				<?= $data['state']; ?>
			</td>
		</tr>

		<!-- form2 -->

		<tr>
			<td>Area to be scanned</td>
			<td>
				<?= $data['sqft']; ?>
			</td>
		</tr>
		<tr>
			<td>Area to be scanned</td>
			<td>
				<?= $data['sqmt']; ?>
			</td>
		</tr>

		<tr>
			<td>What type of area is to be scanned?</td>
			<td>
				<?= $data['typearea']; ?>
			</td>
		</tr>

		<tr>
			<td>Location of Scan Area site
			</td>
			<td>
				<?= $data['Location']; ?>
			</td>
		</tr>

		
		<!-- form3 -->

		<tr>
			<td>Do you also require Scan to BIM Modeling?</td>
			<td>
				<?= $data['yes']; ?>
			</td>
		</tr>
		<tr>
			<td>Choose which software to be used for Modeling?</td>
			<td>
				<?= $data['modeling']; ?>
			</td>
		</tr>

		<tr>
			<td>Types of deliverables expected?</td>
			<td>
				<?= $data['deliverables']; ?>
			</td>
		</tr>

		<tr>
			<td>Please mention the expected LOD(Level of detailing) - LOD Guide
			</td>
			<td>
				<?= $data['LOD']; ?>
			</td>
		</tr>




	</table>

</body>

</html>